"""Phase 11: quantify every MEB decoder against real-car evidence.

The brief asks for, per decoder: raw value, formula, decoded value, Car Scanner
value, absolute error, percentage error, confidence, evidence. Prose notes
asserting "matches Car Scanner" cannot be checked, drift, or be wrong quietly.
This produces the table instead, from tests/fixtures/meb_real_car_vectors.py.

    python tools/validate_decoders.py              # markdown to stdout
    python tools/validate_decoders.py --csv        # machine-readable

The confidence column is the point. A decoder resting on a real capture and one
resting on a source we merely trust look identical in a notes field; here one is
"captured" and the other "derived", and `contested` marks the two places the
sources disagree with us.

Nothing here re-decodes a Car Scanner export: the export carries no raw bytes,
only displayed values, so the comparison is between what our decoder produces
from captured bytes and what Car Scanner displayed for the same quantity.
"""
from __future__ import annotations

import argparse
import csv
import io
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests" / "fixtures"))

from meb_real_car_vectors import CONTESTED, VECTORS  # noqa: E402

from decoders.registry import build_default_registry  # noqa: E402


def _errors(decoded, expected) -> tuple[float | None, float | None]:
    """(absolute, percent) error, or (None, None) when not comparable.

    Dict-valued decoders compare per field, so this returns None for those and
    the caller compares the dicts instead.
    """
    if isinstance(decoded, dict) or isinstance(expected, dict):
        return None, None
    try:
        absolute = abs(float(decoded) - float(expected))
        percent = (absolute / abs(float(expected)) * 100.0
                   if float(expected) else None)
        return absolute, percent
    except (TypeError, ValueError):
        return None, None


def build_rows(profile: str = "meb") -> list[dict]:
    registry = build_default_registry(profile)
    specs = {s.key: s for s in registry.all()}
    rows = []
    for key, raw, expected, evidence, confidence in VECTORS:
        spec = specs.get(key)
        decoded = spec.decode_value(raw) if spec else None
        absolute, percent = _errors(decoded, expected)
        if isinstance(decoded, dict) and isinstance(expected, dict):
            decoded = dict(decoded)
            for field in list(expected):
                got, want = decoded.get(field), expected[field]
                if got is not None:
                    a, p = _errors(got, want)
                    if a is not None:
                        # Worst field decides the row.
                        absolute = max(absolute or 0.0, a)
                        percent = max(percent or 0.0, p or 0.0)
            if absolute is not None:
                percent = absolute / max(
                    abs(float(expected.get("outlet_c", 1) or 1)), 1.0) * 100.0
        rows.append({
            "key": key,
            "did": f"0x{spec.did:04X}" if spec and spec.did else "-",
            "ecu": spec.ecu_key if spec else "-",
            "unit": spec.unit if spec else "",
            "raw": raw.hex().upper(),
            "formula": (spec.notes.split("[")[0].strip()
                        if spec and spec.notes else ""),
            "decoded": decoded,
            "carscanner": expected,
            "abs_err": absolute,
            "pct_err": percent,
            "confidence": confidence,
            "evidence": evidence,
            "contested": CONTESTED.get(key),
            "in_registry": spec is not None,
        })
    return rows


def render_markdown(rows: list[dict]) -> str:
    out = io.StringIO()
    out.write("# MEB decoder validation\n\n")
    out.write("Generated by `tools/validate_decoders.py` from "
              "`tests/fixtures/meb_real_car_vectors.py`. Do not hand-edit.\n\n")
    out.write("`confidence` is the column that matters:\n\n")
    out.write("| value | meaning |\n|---|---|\n")
    out.write("| `captured` | raw bytes and displayed value both from a real "
              "capture; pins the formula outright |\n")
    out.write("| `derived` | raw reconstructed from a documented formula, not "
              "captured here; guards against drift, proves nothing |\n")
    out.write("| `contested` | sources disagree and we have not settled it |\n\n")

    out.write("| key | DID | raw | decoded | CS/expected | abs | % | conf |\n")
    out.write("|---|---|---|---|---|---|---|---|\n")
    for r in rows:
        def fmt(v):
            if v is None:
                return "—"
            if isinstance(v, float):
                return f"{v:g}"
            if isinstance(v, dict):
                return " ".join(f"{k}={x:g}" for k, x in sorted(v.items()))
            return str(v)
        pct = "—" if r["pct_err"] is None else f"{r['pct_err']:.3g}%"
        out.write(f"| `{r['key']}` | {r['did']} | `{r['raw']}` | "
                  f"{fmt(r['decoded'])} | {fmt(r['carscanner'])} | "
                  f"{fmt(r['abs_err'])} | {pct} | "
                  f"{r['confidence']} |\n")

    contested = [r for r in rows if r["contested"]]
    if contested:
        out.write("\n## Contested -- sources disagree with us\n\n")
        for r in contested:
            out.write(f"**`{r['key']}`** ({r['did']})\n\n{r['contested']}\n\n")

    missing = [r for r in rows if not r["in_registry"]]
    if missing:
        out.write("\n## Not in the registry\n\n")
        for r in missing:
            out.write(f"- `{r['key']}`\n")
    return out.getvalue()


def check(rows: list[dict], tolerance_pct: float = 0.01) -> list[str]:
    """Problems worth failing on, as human-readable lines.

    Two classes, both of which have already happened in this repo:

      disagreement  the decoder does not reproduce the expected value from the
                    captured bytes. This is a wrong formula or wrong bytes.
      missing       a vector names a key the decode registry does not define, so
                    nothing checks it and a typo in the key would pass silently.
    """
    problems = []
    for r in rows:
        if not r["in_registry"]:
            problems.append(f"{r['key']}: not in the registry -- nothing "
                            f"validates this vector")
            continue
        if r["pct_err"] is not None and r["pct_err"] > tolerance_pct:
            problems.append(f"{r['key']}: decoded {r['decoded']} != expected "
                            f"{r['carscanner']} ({r['pct_err']:.3g}% off, "
                            f"raw {r['raw']})")
    return problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--profile", default="meb")
    ap.add_argument("--csv", action="store_true")
    args = ap.parse_args(argv)
    rows = build_rows(args.profile)

    if args.csv:
        writer = csv.writer(sys.stdout)
        writer.writerow(["key", "did", "ecu", "unit", "raw", "formula",
                         "decoded", "carscanner", "abs_err", "pct_err",
                         "confidence", "evidence", "contested"])
        for r in rows:
            writer.writerow([r["key"], r["did"], r["ecu"], r["unit"], r["raw"],
                             r["formula"], r["decoded"], r["carscanner"],
                             r["abs_err"], r["pct_err"], r["confidence"],
                             r["evidence"], r["contested"] or ""])
        return 0

    print(render_markdown(rows))
    problems = check(rows)
    if problems:
        print(f"\n{len(problems)} problem(s):", file=sys.stderr)
        for line in problems:
            print(f"  {line}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
